"""Event study: do summary lights generated by stock_web.app's 7-step
dashboard predict subsequent returns?

For each trading day in the long-history series, recompute the 7 lights
using only data up to that day (no look-ahead). Treat any day where the
overall summary label changes as a candidate "event". For each event,
measure forward returns at horizons 5/10/20/40 trading days using
close-to-close.

Compare event-day return distributions vs a same-size random sample of
days from the same series. If the median event return is materially
above the random median, the rule has signal.

Step 8 (institutional) is held at "gray" — we don't have a long T86
history. The summary's strong-entry rule only requires step 8 != red,
so gray still admits all the bullish summaries.

Usage:
    python3 -m backtest.study 2395
    python3 -m backtest.study 2395 5388 --signals strong,sub-strong,reversal
"""
from __future__ import annotations

import argparse
import json
import random
import statistics
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from stock_web import app as _app  # noqa: E402
from stock_web.app import (  # noqa: E402
    _compute_rows, _step_1_market, _step_2_trend, _step_3_momentum,
    _step_4_volume, _step_6_holding, _step_7_exit,
    _step_8_institutional, _summary, _market_for,
    MARKET_TWSE, MARKET_OTC,
)
from backtest.variants import VARIANTS  # noqa: E402

# Active step-3 implementation and event post-filter; swapped by --variant.
_STEP3_FN = _step_3_momentum
_POST_FILTER = None  # callable (rows, idx, steps) -> bool, or None

DATA_DIR = Path(__file__).resolve().parent / "data"

# Historical T86 dumps populated by `backtest/prefetch_t86.py`. Production
# stock_web/app.py only retains 7 days of T86 — that window is way too
# short for an event study. We patch the production `_t86_cached_only`
# lookup to read from these long-history files instead.
_BT_T86_DIR = DATA_DIR / "t86"
_BT_T86OTC_DIR = DATA_DIR / "t86otc"


def _bt_t86_cached_only(date_iso: str, market: str = MARKET_TWSE):
    """Backtest replacement for stock_web.app._t86_cached_only.

    Looks under backtest/data/t86/ and t86otc/. Returns None when the
    file isn't present — the step-8 helper interprets that as
    "skip this day from the institutional window" rather than failing,
    so step 8 degrades to `gray` only when too many days are missing.
    """
    base = _BT_T86_DIR if market == MARKET_TWSE else _BT_T86OTC_DIR
    p = base / f"{date_iso.replace('-', '')}.json"
    if not p.exists():
        return None
    try:
        with p.open() as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


# Override production lookup. Done at import time so any downstream call
# of `_step_8_institutional(..., cached_only=True)` reads our archives.
_app._t86_cached_only = _bt_t86_cached_only

HORIZONS = [5, 10, 20, 40]

STEP_NAMES = ["大盤", "趨勢", "動能", "量能", "持有", "出場", "法人"]


def _adx_above(threshold):
    return lambda rows, idx, steps: (rows[idx].get("adx") or 0) > threshold


def _all_green(idxs):
    return lambda rows, idx, steps: all(steps[i]["light"] == "green" for i in idxs)


def _step_light_eq(step_idx, light):
    return lambda rows, idx, steps: steps[step_idx]["light"] == light


def _composite_and(*preds):
    return lambda rows, idx, steps: all(p(rows, idx, steps) for p in preds)


# Signal definitions used by find_events(). Three flavours:
#   summary:   event = day overall summary label transitions INTO this label
#   step:      event = day a specific step's light transitions INTO `light`
#   composite: event = day a custom predicate transitions from False -> True
SIGNAL_DEFS = {
    "strong":     {"type": "summary", "label": "🟢 多頭擴張"},
    "sub-strong": {"type": "summary", "label": "🟢 多頭發展"},
    "reversal":   {"type": "summary", "label": "🔵 反彈訊號"},
    "exit":       {"type": "summary", "label": "🔴 趨勢轉弱"},
    "watch":      {"type": "summary", "label": "🟠 訊號分歧"},
    "wait":       {"type": "summary", "label": "🟡 盤整中"},
    # Step-level signals — useful for testing whether individual lights
    # have predictive power independent of the summary aggregation.
    "s3-red":     {"type": "step", "step_idx": 2, "light": "red"},
    "s3-green":   {"type": "step", "step_idx": 2, "light": "green"},
    "s2-red":     {"type": "step", "step_idx": 1, "light": "red"},
    "s2-green":   {"type": "step", "step_idx": 1, "light": "green"},
    "s7-red":     {"type": "step", "step_idx": 5, "light": "red"},
    # Composite filters — to test "real strong" entries.
    "s3g-adx25":  {
        "type": "composite", "label": "s3=green & ADX>25",
        "predicate": _composite_and(_step_light_eq(2, "green"), _adx_above(25)),
    },
    "s3g-adx30":  {
        "type": "composite", "label": "s3=green & ADX>30",
        "predicate": _composite_and(_step_light_eq(2, "green"), _adx_above(30)),
    },
    "stack+momo": {
        "type": "composite", "label": "s2=green & s3=green (趨勢+動能)",
        "predicate": _all_green([1, 2]),
    },
    "all4-green": {
        "type": "composite", "label": "s1+s2+s3+s4 全綠 (真正強進場)",
        "predicate": _all_green([0, 1, 2, 3]),
    },
    "trend-pullback": {
        "type": "composite", "label": "s2=green & s3=red (趨勢中回調)",
        "predicate": _composite_and(_step_light_eq(1, "green"),
                                    _step_light_eq(2, "red")),
    },
}

# Backwards compat for any old code paths.
LABEL_OF = {k: v["label"] for k, v in SIGNAL_DEFS.items() if v["type"] == "summary"}


def load_taiex() -> dict:
    path = DATA_DIR / "_taiex.json"
    if not path.exists():
        return {}
    with path.open() as f:
        data = json.load(f)
    return {
        datetime.fromisoformat(k).date(): v
        for k, v in data["closes"].items()
    }


def load_series(code: str) -> list[dict]:
    path = DATA_DIR / f"{code}.json"
    with path.open() as f:
        data = json.load(f)
    return [{
        "date": datetime.fromisoformat(r["date"]).date(),
        "high": r["high"], "low": r["low"],
        "close": r["close"], "lots": r["lots"],
    } for r in data["rows"]]


def _compute_lights(rows: list[dict], end_idx: int,
                    code: str | None = None,
                    market: str = MARKET_TWSE) -> tuple[dict, list[dict]]:
    """Return (summary, steps) at rows[end_idx] using only rows[:end_idx+1].

    Step 7 (法人) reads from the backtest's long-history T86 archive
    (populated by `backtest/prefetch_t86.py`). When `code` is None, or
    when too few T86 files cover the 5-day window, step 7 falls back
    to gray — which mirrors the production behavior when T86 is missing.
    """
    sub = rows[: end_idx + 1]
    window = sub[-20:]
    if len(window) < 2:
        return {"label": None}, []
    last = window[-1]
    prev = window[-2]
    s1 = _step_1_market(window, last)
    s2 = _step_2_trend(window, last)
    s3 = _STEP3_FN(window, last, prev)
    s6 = _step_6_holding(window, last, prev)
    s4 = _step_4_volume(window, last, prev, s3["light"], s6["light"])
    s7 = _step_7_exit(window, last, prev)
    if code:
        # cached_only=True forces the production step-8 helper to read
        # via the patched `_t86_cached_only` — no network calls.
        s8 = _step_8_institutional(window, code, market=market,
                                   cached_only=True)
    else:
        s8 = {"step": 8, "title": "法人認養",
              "light": "gray", "detail": "no code"}
    steps = [s1, s2, s3, s4, s6, s7, s8]
    for i, s in enumerate(steps, 1):
        s["step"] = i
    return _summary(steps), steps


def light_at(rows: list[dict], end_idx: int,
             code: str | None = None,
             market: str = MARKET_TWSE) -> dict:
    return _compute_lights(rows, end_idx, code=code, market=market)[0]


def find_events(rows: list[dict], sig_def: dict,
                start: int = 60,
                code: str | None = None,
                market: str = MARKET_TWSE) -> list[int]:
    """Return indices where the configured signal first triggers.

    sig_def is one of SIGNAL_DEFS values:
      {"type":"summary","label":...} — summary label transition
      {"type":"step","step_idx":N,"light":...} — step-N light transition
    Applies _POST_FILTER if set by the active variant.

    `code` + `market` are forwarded to `_compute_lights` so step 7
    (法人) reads the right T86 archive for this stock; passing None
    keeps step 7 grey and matches the old behavior.
    """
    events = []
    if sig_def["type"] == "summary":
        target = sig_def["label"]
        prev = None
        for i in range(start, len(rows)):
            s, steps = _compute_lights(rows, i, code=code, market=market)
            cur = s.get("label")
            if cur == target and prev != target:
                if _POST_FILTER is None or _POST_FILTER(rows, i, steps):
                    events.append(i)
            prev = cur
        return events
    if sig_def["type"] == "step":
        idx = sig_def["step_idx"]
        target = sig_def["light"]
        prev = None
        for i in range(start, len(rows)):
            _, steps = _compute_lights(rows, i, code=code, market=market)
            cur = steps[idx]["light"] if len(steps) > idx else None
            if cur == target and prev != target:
                if _POST_FILTER is None or _POST_FILTER(rows, i, steps):
                    events.append(i)
            prev = cur
        return events
    if sig_def["type"] == "composite":
        pred = sig_def["predicate"]
        prev = False
        for i in range(start, len(rows)):
            _, steps = _compute_lights(rows, i, code=code, market=market)
            try:
                cur = bool(pred(rows, i, steps))
            except Exception:
                cur = False
            if cur and not prev:
                if _POST_FILTER is None or _POST_FILTER(rows, i, steps):
                    events.append(i)
            prev = cur
        return events
    raise ValueError(f"unknown signal type: {sig_def['type']}")


def forward_return(rows: list[dict], idx: int, horizon: int) -> float | None:
    """Close-to-close return from rows[idx] to rows[idx+horizon]."""
    j = idx + horizon
    if j >= len(rows):
        return None
    a, b = rows[idx]["close"], rows[j]["close"]
    if a is None or b is None or a == 0:
        return None
    return (b - a) / a


def forward_taiex_return(rows: list[dict], idx: int, horizon: int
                         ) -> float | None:
    """Same-window TAIEX return aligned to rows[idx] -> rows[idx+horizon].
    Uses the `taiex` field already attached to each row by _compute_rows."""
    j = idx + horizon
    if j >= len(rows):
        return None
    a, b = rows[idx].get("taiex"), rows[j].get("taiex")
    if a is None or b is None or a == 0:
        return None
    return (b - a) / a


def forward_alpha(rows: list[dict], idx: int, horizon: int) -> float | None:
    """Stock return minus same-window TAIEX return — strips out market beta."""
    r = forward_return(rows, idx, horizon)
    m = forward_taiex_return(rows, idx, horizon)
    if r is None or m is None:
        return None
    return r - m


def percentile(values: list[float], p: float) -> float:
    if not values:
        return float("nan")
    s = sorted(values)
    k = (len(s) - 1) * p
    lo = int(k)
    hi = min(lo + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (k - lo)


def summarize(returns: list[float]) -> dict:
    if not returns:
        return {"n": 0}
    return {
        "n": len(returns),
        "median": statistics.median(returns),
        "mean": statistics.mean(returns),
        "p25": percentile(returns, 0.25),
        "p75": percentile(returns, 0.75),
        "win_pct": sum(1 for r in returns if r > 0) / len(returns),
        "win_above_fees_pct": sum(1 for r in returns if r > 0.006) / len(returns),
    }


def random_baseline(rows: list[dict], n_samples: int, horizon: int,
                    start: int = 60, trials: int = 500) -> dict:
    """Average distribution from `trials` random samples of n_samples
    indices each. Returns aggregate stats."""
    if n_samples == 0:
        return {"n": 0}
    valid_range = range(start, len(rows) - horizon)
    if len(valid_range) < n_samples:
        return {"n": 0}
    medians = []
    means = []
    win_pcts = []
    win_fee_pcts = []
    for _ in range(trials):
        idxs = random.sample(valid_range, n_samples)
        rets = [forward_return(rows, i, horizon) for i in idxs]
        rets = [r for r in rets if r is not None]
        if not rets:
            continue
        medians.append(statistics.median(rets))
        means.append(statistics.mean(rets))
        win_pcts.append(sum(1 for r in rets if r > 0) / len(rets))
        win_fee_pcts.append(sum(1 for r in rets if r > 0.006) / len(rets))
    return {
        "n": n_samples,
        "trials": trials,
        "median": statistics.mean(medians) if medians else float("nan"),
        "mean": statistics.mean(means) if means else float("nan"),
        "win_pct": statistics.mean(win_pcts) if win_pcts else float("nan"),
        "win_above_fees_pct": (statistics.mean(win_fee_pcts)
                               if win_fee_pcts else float("nan")),
    }


def fmt_pct(x: float) -> str:
    if x != x:  # NaN
        return "  n/a"
    return f"{x * 100:+6.2f}%"


LIGHT_CHAR = {"green": "G", "yellow": "Y", "red": "R",
              "orange": "O", "blue": "B", "gray": "-", "none": "·"}


def dump_events(rows: list[dict], events: list[int],
                horizons: list[int] = (5, 10, 20),
                code: str | None = None,
                market: str = MARKET_TWSE) -> None:
    """Per-event line: date, close, n-day stock returns, n-day alpha, step lights.
    Useful for human review of why a signal fired and how it played out."""
    h_cols = " ".join(f"r{h:<3}" for h in horizons)
    a_cols = " ".join(f"a{h:<3}" for h in horizons)
    print(f"    {'date':>10}  {'close':>7}  {h_cols}   {a_cols}  steps   "
          f"momentum_detail")
    for idx in events:
        r = rows[idx]
        rets = [forward_return(rows, idx, h) for h in horizons]
        alphas = [forward_alpha(rows, idx, h) for h in horizons]
        _, steps = _compute_lights(rows, idx, code=code, market=market)
        light_str = "".join(LIGHT_CHAR.get(s["light"], "?") for s in steps)
        s3_detail = steps[2].get("detail", "")
        s7_detail = steps[5].get("detail", "")
        rets_str = " ".join(
            f"{r * 100:+6.2f}" if r is not None else "  n/a "
            for r in rets
        )
        alphas_str = " ".join(
            f"{a * 100:+6.2f}" if a is not None else "  n/a "
            for a in alphas
        )
        close_str = f"{r['close']:7.2f}" if r['close'] is not None else "    n/a"
        print(f"    {r['date']:>10}  {close_str}  {rets_str}   {alphas_str}  "
              f"{light_str}   s3:{s3_detail}")
        # second line: step 7 detail (often relevant for exit signal)
        print(f"    {' ' * 64}        s7:{s7_detail}")


def run_study(code: str, signals: list[str], dump: bool = False) -> None:
    series = load_series(code)
    taiex = load_taiex()
    rows = _compute_rows(series, taiex)
    if not rows:
        print(f"[{code}] no rows after compute")
        return
    market = _market_for(code) or MARKET_TWSE
    print(f"\n=== {code}  ({rows[0]['date']} ~ {rows[-1]['date']}, "
          f"{len(rows)} rows, market={market}) ===")

    for sig in signals:
        sig_def = SIGNAL_DEFS[sig]
        events = find_events(rows, sig_def, code=code, market=market)
        if sig_def["type"] == "summary":
            tag = sig_def["label"]
        elif sig_def["type"] == "step":
            tag = (f"step{sig_def['step_idx']+1}({STEP_NAMES[sig_def['step_idx']]})"
                   f"={sig_def['light']}")
        else:
            tag = sig_def.get("label", "composite")
        print(f"\nSignal: {sig}  ({tag})  events={len(events)}")
        if not events:
            continue

        print(f"   h    n    ret_med    ret_mean  ret_win   alpha_med  "
              f"alpha_mean  alpha_win  |  rand_med  rand_win")
        for h in HORIZONS:
            rets = [forward_return(rows, i, h) for i in events]
            alphas = [forward_alpha(rows, i, h) for i in events]
            rets = [r for r in rets if r is not None]
            alphas = [a for a in alphas if a is not None]
            ret_stats = summarize(rets)
            alpha_stats = summarize(alphas)
            base = random_baseline(rows, len(events), h)
            if ret_stats["n"] == 0:
                continue
            print(f"  {h:>2}  {ret_stats['n']:>3}  "
                  f"{fmt_pct(ret_stats['median'])}  "
                  f"{fmt_pct(ret_stats['mean'])}  "
                  f"{ret_stats['win_pct']*100:>5.1f}%   "
                  f"{fmt_pct(alpha_stats['median'])}   "
                  f"{fmt_pct(alpha_stats['mean'])}     "
                  f"{alpha_stats['win_pct']*100:>5.1f}%   |  "
                  f"{fmt_pct(base['median'])}   "
                  f"{base['win_pct']*100:>5.1f}%")

        if dump:
            dump_events(rows, events, code=code, market=market)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("codes", nargs="+")
    ap.add_argument("--signals", default="strong,sub-strong,reversal,exit",
                    help="comma-separated subset of: " + ",".join(SIGNAL_DEFS))
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--dump", action="store_true",
                    help="print per-event detail lines for human review")
    ap.add_argument("--variant", choices=list(VARIANTS), default="v1",
                    help="step-3 implementation: v1 (production) or v2 "
                         "(adds K>80/RSI6>75 overbought filter)")
    args = ap.parse_args()

    global _STEP3_FN, _POST_FILTER
    step3_fn, post_filter = VARIANTS[args.variant]
    if step3_fn is not None:
        _STEP3_FN = step3_fn
    _POST_FILTER = post_filter
    print(f"[variant: {args.variant}]")

    random.seed(args.seed)
    signals = [s.strip() for s in args.signals.split(",") if s.strip()]
    bad = [s for s in signals if s not in SIGNAL_DEFS]
    if bad:
        print(f"unknown signal(s): {bad}; valid: {list(SIGNAL_DEFS)}")
        sys.exit(2)
    for code in args.codes:
        run_study(code, signals, dump=args.dump)


if __name__ == "__main__":
    main()
